{
 "title": "App Metrics - Web Monitoring - Prometheus",
 "description": "Dashboard to visualize metrics captured by App Metrics ASP.NET Core Middleware 1.2.0, tested with App.Metrics.Formatters.Prometheus 1.1.0  - http://app-metrics.io/",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "query": { "query": "label_values(env)" } },
   { "name": "application", "query": { "query": "label_values(app)" } },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "summarize",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "server", "query": { "query": "label_values(server)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "rpm",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\",server=\"$server\"}[1m])*60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Error %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "application_httprequests_one_minute_error_percentage_rate{env=\"$environment\",app=\"$application\",server=\"$server\"}",
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "query": "SELECT  \"value\" FROM \"application.httprequests__percentage_error_requests\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_httprequests_active{env=\"$environment\",app=\"$application\",server=\"$server\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "apdex" }
   ],
   "targets": [
    {
     "expr": "application_httprequests_apdex{env=\"$environment\",app=\"$application\",server=\"$server\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__apdex",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\",server=\"$server\"}[1m])*60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1 min rate",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15 min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "expr": "rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\",server=\"$server\"}[5m])*60",
     "legendFormat": "5 min rate"
    },
    {
     "expr": "rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\",server=\"$server\"}[15m])*60",
     "legendFormat": "15 min rate"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "application_httprequests_transactions{env=\"$environment\",app=\"$application\",server=\"$server\",quantile=\"0.75\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "75th Percentile",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th Percentile" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "expr": "application_httprequests_transactions{env=\"$environment\",app=\"$application\",server=\"$server\",quantile=\"0.95\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "application_httprequests_transactions{env=\"$environment\",app=\"$application\",server=\"$server\",quantile=\"0.99\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  }
 ]
}